# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindowRTIbzA.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(855, 600)
        MainWindow.setMinimumSize(QSize(855, 600))
        MainWindow.setMaximumSize(QSize(855, 600))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setEnabled(True)
        self.tabWidget.setMinimumSize(QSize(832, 537))
        self.tabWidget.setSizeIncrement(QSize(0, 0))
        self.videoTools = QWidget()
        self.videoTools.setObjectName(u"videoTools")
        self.pButSequenceImageDir = QPushButton(self.videoTools)
        self.pButSequenceImageDir.setObjectName(u"pButSequenceImageDir")
        self.pButSequenceImageDir.setGeometry(QRect(370, 220, 31, 21))
        self.lineEditSequenceImageDir = QLineEdit(self.videoTools)
        self.lineEditSequenceImageDir.setObjectName(u"lineEditSequenceImageDir")
        self.lineEditSequenceImageDir.setGeometry(QRect(110, 220, 251, 20))
        self.label_43 = QLabel(self.videoTools)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(20, 210, 81, 41))
        self.line_18 = QFrame(self.videoTools)
        self.line_18.setObjectName(u"line_18")
        self.line_18.setGeometry(QRect(20, 20, 381, 20))
        self.line_18.setFrameShape(QFrame.HLine)
        self.line_18.setFrameShadow(QFrame.Sunken)
        self.label_55 = QLabel(self.videoTools)
        self.label_55.setObjectName(u"label_55")
        self.label_55.setGeometry(QRect(160, 0, 111, 31))
        self.lineEditPrefix = QLineEdit(self.videoTools)
        self.lineEditPrefix.setObjectName(u"lineEditPrefix")
        self.lineEditPrefix.setGeometry(QRect(90, 50, 111, 20))
        self.label_50 = QLabel(self.videoTools)
        self.label_50.setObjectName(u"label_50")
        self.label_50.setGeometry(QRect(20, 40, 51, 41))
        self.comboBoxSuffix = QComboBox(self.videoTools)
        self.comboBoxSuffix.addItem("")
        self.comboBoxSuffix.addItem("")
        self.comboBoxSuffix.addItem("")
        self.comboBoxSuffix.setObjectName(u"comboBoxSuffix")
        self.comboBoxSuffix.setGeometry(QRect(90, 80, 111, 22))
        self.comboBoxSuffix.setEditable(True)
        self.label_51 = QLabel(self.videoTools)
        self.label_51.setObjectName(u"label_51")
        self.label_51.setGeometry(QRect(20, 70, 51, 41))
        self.spinBoxZfill = QSpinBox(self.videoTools)
        self.spinBoxZfill.setObjectName(u"spinBoxZfill")
        self.spinBoxZfill.setGeometry(QRect(350, 50, 42, 22))
        self.spinBoxZfill.setMinimum(1)
        self.spinBoxZfill.setMaximum(10)
        self.spinBoxZfill.setValue(7)
        self.label_18 = QLabel(self.videoTools)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(280, 50, 41, 21))
        self.pButSeq2Video = QPushButton(self.videoTools)
        self.pButSeq2Video.setObjectName(u"pButSeq2Video")
        self.pButSeq2Video.setGeometry(QRect(50, 290, 131, 31))
        self.pButAnnotationPath = QPushButton(self.videoTools)
        self.pButAnnotationPath.setObjectName(u"pButAnnotationPath")
        self.pButAnnotationPath.setGeometry(QRect(370, 250, 31, 21))
        self.lineEditAnnotationPath = QLineEdit(self.videoTools)
        self.lineEditAnnotationPath.setObjectName(u"lineEditAnnotationPath")
        self.lineEditAnnotationPath.setGeometry(QRect(110, 250, 251, 20))
        self.line = QFrame(self.videoTools)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(410, 40, 20, 461))
        self.line.setFrameShape(QFrame.VLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.line_19 = QFrame(self.videoTools)
        self.line_19.setObjectName(u"line_19")
        self.line_19.setGeometry(QRect(20, 360, 381, 20))
        self.line_19.setFrameShape(QFrame.HLine)
        self.line_19.setFrameShadow(QFrame.Sunken)
        self.label_56 = QLabel(self.videoTools)
        self.label_56.setObjectName(u"label_56")
        self.label_56.setGeometry(QRect(150, 340, 111, 31))
        self.label_44 = QLabel(self.videoTools)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(20, 380, 81, 41))
        self.pButVideoPath = QPushButton(self.videoTools)
        self.pButVideoPath.setObjectName(u"pButVideoPath")
        self.pButVideoPath.setGeometry(QRect(370, 390, 31, 21))
        self.lineEditVideoPath = QLineEdit(self.videoTools)
        self.lineEditVideoPath.setObjectName(u"lineEditVideoPath")
        self.lineEditVideoPath.setGeometry(QRect(110, 390, 251, 20))
        self.pButVideo2Sequence = QPushButton(self.videoTools)
        self.pButVideo2Sequence.setObjectName(u"pButVideo2Sequence")
        self.pButVideo2Sequence.setGeometry(QRect(130, 430, 131, 31))
        self.line_20 = QFrame(self.videoTools)
        self.line_20.setObjectName(u"line_20")
        self.line_20.setGeometry(QRect(20, 190, 381, 20))
        self.line_20.setFrameShape(QFrame.HLine)
        self.line_20.setFrameShadow(QFrame.Sunken)
        self.label_57 = QLabel(self.videoTools)
        self.label_57.setObjectName(u"label_57")
        self.label_57.setGeometry(QRect(150, 170, 111, 31))
        self.spinBoxStartIdx = QSpinBox(self.videoTools)
        self.spinBoxStartIdx.setObjectName(u"spinBoxStartIdx")
        self.spinBoxStartIdx.setGeometry(QRect(90, 110, 42, 22))
        self.spinBoxStartIdx.setMinimum(0)
        self.spinBoxStartIdx.setMaximum(50000)
        self.spinBoxStartIdx.setValue(1)
        self.label_19 = QLabel(self.videoTools)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(20, 110, 61, 21))
        self.spinBoxInterval = QSpinBox(self.videoTools)
        self.spinBoxInterval.setObjectName(u"spinBoxInterval")
        self.spinBoxInterval.setGeometry(QRect(90, 140, 42, 22))
        self.spinBoxInterval.setMinimum(1)
        self.spinBoxInterval.setMaximum(100)
        self.spinBoxInterval.setValue(1)
        self.label_20 = QLabel(self.videoTools)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(20, 140, 61, 21))
        self.spinBoxEndIdx = QSpinBox(self.videoTools)
        self.spinBoxEndIdx.setObjectName(u"spinBoxEndIdx")
        self.spinBoxEndIdx.setGeometry(QRect(350, 110, 42, 22))
        self.spinBoxEndIdx.setMinimum(-1)
        self.spinBoxEndIdx.setMaximum(50000)
        self.spinBoxEndIdx.setValue(-1)
        self.label_22 = QLabel(self.videoTools)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(280, 110, 31, 21))
        self.spinBoxFPS = QSpinBox(self.videoTools)
        self.spinBoxFPS.setObjectName(u"spinBoxFPS")
        self.spinBoxFPS.setGeometry(QRect(350, 80, 42, 22))
        self.spinBoxFPS.setMinimum(1)
        self.spinBoxFPS.setMaximum(70)
        self.spinBoxFPS.setValue(30)
        self.label_23 = QLabel(self.videoTools)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(280, 80, 41, 21))
        self.comboBoxAnnotation = QComboBox(self.videoTools)
        self.comboBoxAnnotation.addItem("")
        self.comboBoxAnnotation.addItem("")
        self.comboBoxAnnotation.addItem("")
        self.comboBoxAnnotation.setObjectName(u"comboBoxAnnotation")
        self.comboBoxAnnotation.setGeometry(QRect(20, 250, 81, 22))
        self.line_21 = QFrame(self.videoTools)
        self.line_21.setObjectName(u"line_21")
        self.line_21.setGeometry(QRect(440, 20, 381, 20))
        self.line_21.setFrameShape(QFrame.HLine)
        self.line_21.setFrameShadow(QFrame.Sunken)
        self.pButViewTracks = QPushButton(self.videoTools)
        self.pButViewTracks.setObjectName(u"pButViewTracks")
        self.pButViewTracks.setGeometry(QRect(220, 290, 131, 31))
        self.spinBoxLineWidth = QSpinBox(self.videoTools)
        self.spinBoxLineWidth.setObjectName(u"spinBoxLineWidth")
        self.spinBoxLineWidth.setGeometry(QRect(350, 140, 42, 22))
        self.spinBoxLineWidth.setMinimum(1)
        self.spinBoxLineWidth.setMaximum(10)
        self.spinBoxLineWidth.setValue(1)
        self.label_21 = QLabel(self.videoTools)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(280, 140, 61, 21))
        self.tabWidget.addTab(self.videoTools, "")
        self.sequenceTools = QWidget()
        self.sequenceTools.setObjectName(u"sequenceTools")
        self.label_58 = QLabel(self.sequenceTools)
        self.label_58.setObjectName(u"label_58")
        self.label_58.setGeometry(QRect(140, 10, 111, 31))
        self.pButRenameFolder = QPushButton(self.sequenceTools)
        self.pButRenameFolder.setObjectName(u"pButRenameFolder")
        self.pButRenameFolder.setGeometry(QRect(110, 130, 131, 31))
        self.label_45 = QLabel(self.sequenceTools)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(10, 50, 81, 41))
        self.pButRenameFolderDir = QPushButton(self.sequenceTools)
        self.pButRenameFolderDir.setObjectName(u"pButRenameFolderDir")
        self.pButRenameFolderDir.setGeometry(QRect(360, 60, 31, 21))
        self.lineEditRenameFolderDir = QLineEdit(self.sequenceTools)
        self.lineEditRenameFolderDir.setObjectName(u"lineEditRenameFolderDir")
        self.lineEditRenameFolderDir.setGeometry(QRect(80, 60, 271, 20))
        self.line_22 = QFrame(self.sequenceTools)
        self.line_22.setObjectName(u"line_22")
        self.line_22.setGeometry(QRect(10, 30, 381, 20))
        self.line_22.setFrameShape(QFrame.HLine)
        self.line_22.setFrameShadow(QFrame.Sunken)
        self.checkBoxOriginIndexSort = QCheckBox(self.sequenceTools)
        self.checkBoxOriginIndexSort.setObjectName(u"checkBoxOriginIndexSort")
        self.checkBoxOriginIndexSort.setGeometry(QRect(10, 100, 131, 16))
        self.tabWidget.addTab(self.sequenceTools, "")

        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 855, 23))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.pButSequenceImageDir.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.label_43.setText(QCoreApplication.translate("MainWindow", u"Sequence Dir:", None))
        self.label_55.setText(QCoreApplication.translate("MainWindow", u"Common Configs", None))
        self.label_50.setText(QCoreApplication.translate("MainWindow", u"Prefix:", None))
        self.comboBoxSuffix.setItemText(0, QCoreApplication.translate("MainWindow", u".jpg", None))
        self.comboBoxSuffix.setItemText(1, QCoreApplication.translate("MainWindow", u".png", None))
        self.comboBoxSuffix.setItemText(2, QCoreApplication.translate("MainWindow", u".jpeg", None))

        self.label_51.setText(QCoreApplication.translate("MainWindow", u"Suffix:", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Zfill:", None))
        self.pButSeq2Video.setText(QCoreApplication.translate("MainWindow", u"Make Video", None))
        self.pButAnnotationPath.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.label_56.setText(QCoreApplication.translate("MainWindow", u"Video to Sequence", None))
        self.label_44.setText(QCoreApplication.translate("MainWindow", u"Video Path:", None))
        self.pButVideoPath.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.pButVideo2Sequence.setText(QCoreApplication.translate("MainWindow", u"Extract Frames", None))
        self.label_57.setText(QCoreApplication.translate("MainWindow", u"Sequence to Video", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"Start:", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"Interval:", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"End:", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"FPS:", None))
        self.comboBoxAnnotation.setItemText(0, QCoreApplication.translate("MainWindow", u"None", None))
        self.comboBoxAnnotation.setItemText(1, QCoreApplication.translate("MainWindow", u"Detection", None))
        self.comboBoxAnnotation.setItemText(2, QCoreApplication.translate("MainWindow", u"Tracking", None))

        self.pButViewTracks.setText(QCoreApplication.translate("MainWindow", u"View Tracks", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"LineWidth:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.videoTools), QCoreApplication.translate("MainWindow", u"VideoTools", None))
        self.label_58.setText(QCoreApplication.translate("MainWindow", u"Batch Rename", None))
        self.pButRenameFolder.setText(QCoreApplication.translate("MainWindow", u"Rename", None))
        self.label_45.setText(QCoreApplication.translate("MainWindow", u"Folder Dir:", None))
        self.pButRenameFolderDir.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.checkBoxOriginIndexSort.setText(QCoreApplication.translate("MainWindow", u"Origin Index Sort", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sequenceTools), QCoreApplication.translate("MainWindow", u"Other", None))
    # retranslateUi

